Taka1304/ds-lms-demo

- src/app/page.tsx
- src/components/features/landing/cta.tsx
- src/components/features/landing/features.tsx
- src/components/features/landing/hero.tsx
- src/components/layout/footer.tsx
- src/components/ui/flip-words.tsx
close #7 
サービス名とか適当なので後で変える必要ありです
> Landing pageの仮作成

- src/lib/auth.ts
>  🐛 fix: 姓と名が逆で格納されている問題を修正

- .vscode/extensions.json
.vscode/extensions.json
に便利な拡張機能を入れておきました
> 🔧 オススメの拡張機能を追加

- next.config.ts
- src/lib/auth.ts
next.config.tsにsupabaseのドメインを許容するように修正
CustomLoaderにした方がよいのかもしれない、要検証。
authのpropsリレーで継承されていないことがあったのを修正
- Close #69 
- 変更点1
- 変更点2
> ユーザーの画像表示対応

- src/app/api/[[...route]]/route.ts
- src/app/api/[[...route]]/users/getUser.ts
- src/app/api/[[...route]]/users/index.ts
- src/app/api/[[...route]]/users/updateUser.ts
ユーザー詳細取得APIの実装
ユーザー情報更新APIの実装
- Close #67 
- Close #68
> #67 #68 ユーザー関連API実装

- .vscode/settings.json
- src/app/api/[[...route]]/middleware/auth.ts
- Close # 
- ミドルウェアの違いをコメント追記
- gitmojiの設定を追加。拡張機能を通してコミットメッセージに簡単に絵文字を付与可能
> 設定、コメント追記等

- prisma/migrations/20250414053416_test_result/migration.sql
- prisma/schema.prisma
- src/app/api/[[...route]]/courses/problems/getSubmission.ts
- src/app/api/[[...route]]/courses/problems/index.ts
- src/app/api/[[...route]]/courses/problems/submitProblem.ts
テーブル変更、API実装
- Close #73 
- ついでにgetも実装した（よくない）
> #73 getSubmission, submitProblemの実装

- src/app/error.tsx
- src/app/not-found.tsx
- src/app/students/page.tsx
404ページ（not-found.tsx）：ページが見つからない
500ページ（error.tsx）：サーバ内部エラー
ページの作成
- Close #78 
- app/not-found.tsxを作成
- ホームボタン（app/）とお問い合わせ（/contact）ボタンを実装
- app/error.tsx を作成
- 再試行ボタンとお問い合わせ（/contact）へボタンを実装
404ページ画面
500ページ画面
・レイアウトの部分
・404ページに行った際ホームへ戻るボタンを実装したのですが、app/page.tsx（ホーム画面）へ戻る動作にしています。
遷移先としてこの実装で問題ないか見てほしいです。
・git commit した際にstudentsのpage.tsxが勝手に変更されます。動作はしているようなんですが、確認お願いします。
> feat: not-found.tsxとerror.tsxの追加

- prisma/migrations/20250419084700_fix_submission/migration.sql
- prisma/schema.prisma
- src/app/api/[[...route]]/courses/problems/index.ts
- src/app/api/[[...route]]/courses/problems/updateSubmission.ts
- Close #95 
- schemaを一部更新
- submissionに挑戦開始時刻を追加
- testResultsにそれぞれstatusやmemoryUsage, timeUsageを持つように修正
> #95 updateSubmissionの実装

- prisma/migrations/20250419143809_default_code/migration.sql
- prisma/schema.prisma
- src/app/students/courses/[courseId]/[problemId]/page.tsx
- src/features/problems/components/programming-interface.tsx
Issueを参照
- Close #97
-  
- スキーマ変更
- Editorのデフォルト値に反映
> #97 デフォルトの入力値を反映させる

- src/features/problems/components/python-execution-provider.tsx
`\r\n` を改行文字として解釈し，適切にinput()に渡せるように挙動を修正
- Close #101 
- 変更点1
- 変更点2
> #101 複数行入力への対応

- src/app/students/courses/page.tsx
app/students/courses
コース一覧のHeaderの色をテーマカラーに合わせる
- Close #92 
- 変更点1
- 今回はapp/students/courses/page.tsxを修正
ヘッダーにテーマカラーが適用されるように修正しました。
- 変更点2
> #92 Headerの色をテーマカラーに合わせる

- src/app/error.tsx
- src/app/layout.tsx
- src/app/not-found.tsx
- Close # 
- Head コンポーネントを削除し、Script を body 内に移動
- `text-center`が被っていたため重複を削除
> Umamiが動作していない不具合の修正

- src/app/privacy/page.tsx
プライバシーポリシーページの作成
- Close # 
/src/app/privacy/page.tsxに配置しました
このプルリクエストをレビューしてコメントする際は日本語でお願いします。 -->
> #55 プライバシーポリシーページの作成

- src/app/auth/signin/page.tsx
- src/features/problems/components/programming-interface.tsx
- src/features/problems/components/python-execution-provider.tsx
- Close #77 
- interruptExecutionで実行中のワーカーを削除し、新規ワーカーを割り当てる
- auth/signinのリンクを修正
- auth/signinのgetServerSessionにauthOptionsが入っていない問題を修正
> #77 TLE発生時に再実行できないバグを修正

- src/features/problems/components/programming-interface.tsx
CodeをuseStateで管理せず、コマンドに渡す関数をuseRefで管理することで、更新しつつ、レンダリングを抑制する。
toastの実装
- Close #87 
- CodeをuseStateで管理せず、コマンドに渡す関数をuseRefで管理することで、更新しつつ、レンダリングを抑制する。
- toastの実装
> Refactor: feat/432

- src/app/api/[[...route]]/courses/problems/submitProblem.ts
- src/features/problems/components/programming-interface.tsx
- src/hooks/use-start-time-tracker.ts
> #88 問題への挑戦開始時刻を追加

- src/features/problems/components/python-execution-provider.tsx
- Close #140 
- Close #141  
- 変更点1
- 変更点2
> Fix: #140 #141

- prisma/migrations/20250526111148_ext_expires_in/migration.sql
- prisma/schema.prisma
> 認証でOAuthAccountNotLinkedが発生するのを修正

- src/app/students/courses/[courseId]/page.tsx
> Fix🐛: UserProgressが0の場合に対処

- src/app/api/[[...route]]/courses/getCourse.ts
- src/app/students/courses/[courseId]/page.tsx
- src/features/courses/[courseId]/components/card-content.tsx
UserProgressの変更が上手くいっていないため、submissionで進捗状況を管理するように暫定処理を行う
- Close #150 
- 変更点1
- 変更点2
> #150 進捗状況の管理を修正 解答済みの表示

- src/app/api/[[...route]]/dashboard/activityHeatmap.ts
- src/app/manage/courses/[courseId]/new/page.tsx
- src/app/manage/page.tsx
- src/app/profile/page.tsx
- src/app/students/courses/[courseId]/[problemId]/[submissionId]/page.tsx
- src/app/students/courses/[courseId]/[problemId]/challenge/page.tsx
- src/app/students/courses/[courseId]/[problemId]/page.tsx
- src/app/students/courses/[courseId]/page.tsx
- src/app/students/courses/page.tsx
- src/components/ui/breadcrumb.tsx
- src/components/ui/carousel.tsx
- src/features/dashboard/container/activity-heatmap.tsx
- src/features/dashboard/container/progress-overview.tsx
- src/features/dashboard/container/recent-submissions.tsx
> Fix🐛: ユーザーIDをクエリに追加し、セッションから取得するように修正

- src/features/dashboard/recent-submissions.tsx
> Feat✨: 0件の場合の表示を追加

- next.config.ts
> Fix🐛: 本番環境のsupabase storageから画像が取得できない問題を修正

- prisma/migrations/20250703021617_add_answer/migration.sql
- prisma/schema.prisma
- Close #178
- Answerテーブルをスキーマに追加する
> issue178 :  Answerテーブルを追加

- src/features/problems/components/console-view.tsx
- src/features/problems/components/programming-interface.tsx
- Close #152 
- ConsoleをResizableにする
- 問題文が見切れてしまう問題を修正ｓ
> Feat✨: ConsoleをResizableにする
